sonar.projectKey=my-apache-site
sonar.projectName=my-apache-site
sonar.sources=.
sonar.tests=tests
sonar.exclusions=node_modules/**,tests/**,reports/**,coverage/**,package-lock.json,Jenkinsfile
sonar.sourceEncoding=UTF-8